version: "3"

services:
  news:
    build: .
    image: tech_news_image
    volumes:
      - ./:/app
    container_name: tech_news
    tty: true # docker run -t
    stdin_open: true # docker run -i
    command: bash
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      - DB_HOST=mongodb
      - FLASK_APP=tests/__init__.py
      - FLASK_ENV=development
      - TEMPLATES_AUTO_RELOAD=True
      - PYTHONUNBUFFERED=1
      - APPLY_TO_ALL=True
    ports:
      - 5000:5000
    networks:
      - tech_news_net

  mongodb:
    image: mongo:4.4.14
    container_name: tech_news_db
    volumes:
      - ./:/app
    restart: unless-stopped
    ports:
      - 27017:27017
    networks:
      - tech_news_net

networks:
  tech_news_net:
    driver: bridge
